ALTER USER sys IDENTIFIED BY password;

ALTER SESSION SET CONTAINER = orclpdb1;

CREATE USER medirecords_3235 IDENTIFIED BY password;

GRANT CREATE SESSION TO medirecords_3235;

GRANT CREATE TABLE TO medirecords_3235;

ALTER USER medirecords_3235 QUOTA UNLIMITED ON USERS;

